server:
  port: 9527
eureka:
  client:
    service-url: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: cloud-server-zuul # 实例名称
    prefer-ip-address: true  # 显示ip地址


# info:
